---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: meta-webhook.infra.rwx.im
spec:
  secretName: meta-webhook.infra.rwx.im-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - meta-webhook.infra.rwx.im
