---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meta-webhook
  labels:
    app: meta-webhook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meta-webhook
  template:
    metadata:
      labels:
        app: meta-webhook
      annotations:
        linkerd.io/inject: enabled
        vault.security.banzaicloud.io/vault-role: meta
        vault.security.banzaicloud.io/vault-addr: "https://vault.default:8200"
        vault.security.banzaicloud.io/vault-tls-secret: vault-tls
    spec:
      containers:
      - name: meta-webhook
        image: rg.nl-ams.scw.cloud/uplink/meta-webhook:main
        env:
        - name: RACK_ENV
          value: production
        - name: META_RPC_URL
          value: tcp://meta-rpc:31337
        - name: META_RPC_SECRET
          value: vault:secret/data/meta#RPC_SECRET
        - name: META_WEBHOOK_TOKEN
          value: vault:secret/data/meta#WEBHOOK_TOKEN
      imagePullSecrets:
      - name: uplink-nl-ams-scw-registry
