apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: uplink-nl-ams-scw-registry
  namespace: meta-webhook
spec:
  encryptedData:
    .dockerconfigjson: AgAL4hxBgLI6L4/Sv938E3HQdUy7dUR4y8/v4Q47OhImuLg+tqXDqdevAQkWTPpXXhGAtbZe+GhJYDBQ/QFcCUbP/hJKd6/nUngGiP0JwthHywnIJgRifAQwqz5mgwRBb/Zb+gNQqKaFqzfAImOJSbYfOVfaXPW9uhvTbBxXOrCiRr8141SmJQnwSsHLEGAssRtQ+wznjEkpNzGkJxWWYF0WksdoDPTXS6WkEnYcHl4KiMHN6HAFKIJOMtV5kxhyMasofQUoB2gtY5sOAFaGfnSaP9WmLvIN3Nz5QHnvfztrs+vwNerGIhTN0SRBeRVD+corcFOavxiOiZkhM+BCEb3ZGvI1Q19lHnTIja5MzVWaFOyBBQvIgrhVqGYjuxh9CHHD9tH/KAyrStkAnModcgnhUFmUW4EjbowGwPW9O6VJgsmsK4H2vtRCVpOWh9OMEtglXjUOGgFb2dXQyX0xQjaAlVRN1tgR7xWRScW0vRkutwUxje4rPFMX8OCIo5CNKYhMFxaCpXlY8vVSAKqgHxcUpHw4sj61VTMV54UnPiIjsyPWO7GVzBWtIigWsiI9TCA6H8LBg3mjCoXeWFaV0CVLI/GKqUO6ZYK1xMsslih1Jrr4XZ86c/W1m81qvzdS72yMXQpnuNH0Sb5thravV3boEJiP6wQVH4qBmQ/I2vgbJSE4hN/ZJZdAS8HA5ktRFc45nu2kFrbg4fO7/HdfaTyLm+mRzWQcr18MnynnbIngUWN7RP1WFAAjVofb2U3Um/FW70Rl7ipmgEuwK6fIOuFBn6zDJtTm79+hGFW6KlcefCFHIO/rASRCcJTBhTwptfIFCgAUIcAqbNKwySan+M/WwWDAdvvcDucDVn054UClCf5xz2J8
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: uplink-nl-ams-scw-registry
      namespace: meta-webhook
    type: kubernetes.io/dockerconfigjson

