---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: uplink-nl-ams-scw-registry
  namespace: meta-webhook
spec:
  encryptedData:
    .dockerconfigjson: AgDWlws9pG7PM+GCBtIiLwmhjh3vR9/ZF+2kOLQzL/oxusr2Feri4F4wX5K0ECZH+wNnStI/tdqUDZgw29C/Q/3Db8Q9S7z7EvOc+aFNiabAO9Bqm6EK0sXlDNhEDql1r1Eku2YNgj6djcz8zMirX4zfvUKP0wmganxuwKvfkjQHwH6CWjWsROa3fi2+3V1wBnI6vHSQPf0eYp8qVBSYUMRCw8mxKJjH8Jp4BU3nh5W8gB3woCcvgpRel1W+RPfIrxjmeNw6w6QRKfsBEFlswH4H6paEO5Dt/BNsl6VklK0L1YBaSTSa/5/r4rR1budRkLoImcIzSUGqDfAcYAgi5/BKL7emwQCp6mIjf9FBsHKYsG7pGigeF4fk3ItENVRTa8yKeB18fOpgAeKN6On51e6jTF8n7mHaeMuB981Gal6h0O3O1TaHDMidaOvqrZTXnpU/rqn54zyig4NVQLKuZ8VxAGYldqGHHMbFrfCuX+CrDvmzq5L0wi94IeuM2dmWSP3iS2KwgZDtmjmzyWkfTBVEuCY0Iiw35HovDjwMI6ufWJUdSsxWOhCBfVkoAd/lBZlsG8erButhgV2X64bpRn3XJqHncnYt7t8mCeQfuRXa5+Th67IUVwfslcdiwi9x+BJjs202NOBRwlYJHndTyeDtq1Au5DqbrsECn9epq99ELr3qRGhICK7s5VJyfiDMmlXvHPzdvQKg0J5rlmMJkHgS7VgD86PdUOHrAFKG5p+a7T+whwZphsXT+vpQh8F1rUIL1oC0sNN/2Ig3TaZ/Ke3jKr0s4bwGd1ACMkXwoYoYrHq/1MHIA/5p9SCgp1ZD+v0DRuXGwDeob4VhdelZoi6lwqnNyuoIHdi6Jk7oFSuDbYjIXipU
  template:
    metadata:
      creationTimestamp: null
      name: uplink-nl-ams-scw-registry
      namespace: meta-webhook
    type: kubernetes.io/dockerconfigjson
