patches:
- path: ./patches/deployment.yaml
  target:
    kind: Deployment

images:
- name: meta
  newName: ghcr.io/rwx-labs/meta-oss
  newTag: sha-4726a19b0caa61a0183e233a10bc17c198e98507
- name: meta-mail_reader
  newName: rg.nl-ams.scw.cloud/uplink/meta-mail_reader
  newTag: 0.1.8

resources:
- ./manifests/sealedsecret.uplink-nl-ams-scw-registry.yaml
- ./manifests/sealedsecret.meta-env.yaml
- ./manifests/sealedsecret.meta-mailreader.yaml
- ./manifests/sealedsecret.postgres-backup.yaml
- ../../base/meta
- ./manifests/cluster.postgres.yaml
- ./manifests/scheduledbackup.postgres.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
