patches:
- path: ./patches/deployment.yaml
  target:
    kind: Deployment

images:
- name: rg.nl-ams.scw.cloud/uplink/meta
  newTag: sha-b4e936baf0892ee69b60da0d07d45bb7abb2f5b8

resources:
- ./manifests/sealedsecret.uplink-nl-ams-scw-registry.yaml
- ./manifests/sealedsecret.meta-env.yaml
- ./manifests/sealedsecret.meta-mailreader.yaml
- ./manifests/sealedsecret.postgres-backup.yaml
- ../../base/meta
# - ./manifests/cluster.postgres.yaml
- ./manifests/scheduledbackup.postgres.yaml
