patches:
- path: ./patches/deployment.yaml
  target:
    kind: Deployment

images:
- name: rg.nl-ams.scw.cloud/uplink/meta
  newTag: sha-5ad0827933c20f906ab9020a2606f90aab03be44

resources:
- ./manifests/sealedsecret.uplink-nl-ams-scw-registry.yaml
- ./manifests/sealedsecret.meta-env.yaml
- ./manifests/sealedsecret.meta-mailreader.yaml
- ./manifests/sealedsecret.postgres-backup.yaml
- ../../base/meta
- ./manifests/cluster.postgres.yaml
- ./manifests/scheduledbackup.postgres.yaml
