patches:
- path: ./patches/deployment.yaml
  target:
    kind: Deployment

images:
- name: meta
  newName: rg.nl-ams.scw.cloud/uplink/meta
  newTag: sha-7c0cb684ef12a4a5c84b52c3656be2361648b924
- name: meta-mail_reader
  newName: rg.nl-ams.scw.cloud/uplink/meta-mail_reader
  newTag: 0.1.8

resources:
- ./manifests/sealedsecret.uplink-nl-ams-scw-registry.yaml
- ./manifests/sealedsecret.meta-env.yaml
- ./manifests/sealedsecret.meta-mailreader.yaml
- ./manifests/sealedsecret.postgres-backup.yaml
- ../../base/meta
- ./manifests/cluster.postgres.yaml
- ./manifests/scheduledbackup.postgres.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
