patches:
- path: ./patches/deployment.yaml
  target:
    kind: Deployment

images:
- name: rg.nl-ams.scw.cloud/uplink/meta
  newTag: sha-1c9a76a6c903d536fe28bfc6c83ab56e94939d4d

resources:
- ./manifests/sealedsecret.uplink-nl-ams-scw-registry.yaml
- ./manifests/sealedsecret.meta-env.yaml
- ./manifests/sealedsecret.meta-mailreader.yaml
- ./manifests/sealedsecret.postgres-backup.yaml
- ../../base/meta
# - ./manifests/cluster.postgres.yaml
- ./manifests/scheduledbackup.postgres.yaml
