---
namespace: meta
resources:
- manifests/persistentvolumeclaim.yaml
- manifests/sealedsecret.uplink-nl-ams-scw-registry.yaml
- manifests/deployment.yaml
- manifests/service.yaml
- manifests/rbac.yaml
