replicaCount: 3

image:
  repository: ghcr.io/rwx-im/meta-webdriver
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "sha-3f3f6eec6cca65c2a3aa1cb82cab9230847b65b5"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 3000

extraEnv:
- name: RUST_BACKTRACE
  value: full
- name: RUST_LOG
  value: meta_webdriver=debug

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
