---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meta
  namespace: meta
spec:
  # Template for the created pods
  template:
    metadata:
      namespace: meta
    spec:
      initContainers:
      - name: meta-migrate-db
        image: meta:latest
        command: ["/bin/sh", "-c", "mkdir /meta/cache; bundle exec sequel -m /meta/migrations \"${DATABASE_URL}\""]
        volumeMounts:
        - name: meta-cache
          mountPath: /meta/cache
        envFrom:
        - secretRef:
            name: meta-env
      containers:
      # The bot container
      - name: meta
        image: meta:latest
        env:
        - name: TZ
          value: Europe/Copenhagen
        args: [-v]
        securityContext:
          capabilities:
            drop:
            - NET_RAW
        volumeMounts:
        - name: meta-cache
          mountPath: /meta/cache
        - name: meta-webm
          mountPath: /data/webm
        envFrom:
        - secretRef:
            name: meta-env

      # The mail reader container
      - name: mail-reader
        image: meta-mail_reader:0.1.8
        env:
        - name: S3_BUCKET_NAME
          value: 7td20i4n5csfoq1w
        - name: AWS_REGION
          value: eu-north-1
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: meta-mailreader
              key: aws-access-key
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: meta-mailreader
              key: aws-secret-access-key
        - name: IMAP_USERNAME
          valueFrom:
            secretKeyRef:
              name: meta-mailreader
              key: imap-username
        - name: IMAP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: meta-mailreader
              key: imap-password
        - name: RPC_SECRET
          valueFrom:
            secretKeyRef:
              name: meta-mailreader
              key: rpc-secret
        securityContext:
          capabilities:
            drop:
            - NET_RAW
      volumes:
      - name: meta-cache
        persistentVolumeClaim:
          claimName: meta-cache
      - name: meta-webm
        emptyDir: {}
