image:
  repository: ghcr.io/rwx-im/meta
  pullPolicy: IfNotPresent
  tag: "edge"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000
  #

# Extra environment variables to pass to the pods.
podExtraEnv: []

blur:
  environment: production


securityContext:
  capabilities:
    drop:
    - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
