apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "meta-oss.fullname" . }}
  labels:
    {{- include "meta-oss.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "meta-oss.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- include "meta-oss.vaultAnnotations" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "meta-oss.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        env:
        - name: BLUR_ENV
          value: {{ default "production" .Values.blur.environment }}
        {{- range $key, $value := .Values.podExtraEnv }}
        - name: {{ tpl $key $ }}
          value: {{ tpl $value $ }}
        {{- end }}
        args: [-v]
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
