---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: uplink-nl-ams-scw-registry
  namespace: meta
spec:
  encryptedData:
    .dockerconfigjson: AgB7469R3y6mKaHYLMeK/UrhkkcWQtdzO3zAtYJ/Lh1/OlH83oxk1Oo3wLqLOIIJ/4pxidyzsfJDvgusNkEj1Wzj0OBQkjX8c7Hyeg+Lqc0fKBEggRQ8uJFkJSiRcgGYG6Rgqtcf3r76VtByvXi0D6GWznb/0kD6ZWfk+njzIAyh2g0eohG+4DxCVyLI6zo2EYdqAHvj6lNVxZIP4uUwGrbfpyaIzSGKUr7zb0aD+y8w/ML9joN0hsF897PD5itIB5ogJ4PoAge0FlADrnRlw0CzIOz1ykeGZkeTH6AYkEto4YexTxmr6iMcLSysnwjMKiq+R8Z8v+vEvEHKvFYR/7Zp0HVt5Gk81S2lfhqY79r/LCqQsvUG3+GkytjicP9lPiQSP0Vh7d1CULt16G1026YXl2NkXD3Gmg4r5E6X3+Mj/MiItB2Clq4IoAbXVPtSKBY+8QIB6R3ys3qi0hBaGa/9n1BjBFRs2hMa8NtAXqYU6YRxhQF/soT75Bie0rm2pp8mtHVDVYEgX2T5e5VAHaaJY8P8j/eioyH4quvgbP2apFcukLOHImjSWynDAoAyANR/kT8clpaThvsQZ7oITxa8GBm6aVYYdgUgp1FxcSIZ21jOOvz+UV3/UTXtsSYqHd51+wF6UxT8rnZ1sNWiHcyWY31j5QTewRCIJf6z2jejTqS4TlwHW/7AM2wyt6QYGhnH52yhIhTGuLjtReNcONvCRzX8iwnPO2f/IGB8ijz3HbZC2SDdW1J9jVjfzk/AQAXL5bQwgC4rCkw6XDIgPvloGa29UxO5FUyXOgH9mmYTFDN3w7LvqUrm3rP0nPdgmI8FuyW8uqXcUffwBz0kFUL9njzQt/XeyNZo66lmu1g56LVvGL3N
  template:
    metadata:
      creationTimestamp: null
      name: uplink-nl-ams-scw-registry
      namespace: meta
    type: kubernetes.io/dockerconfigjson
