apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  instances: 2
  backup:
    barmanObjectStore:
      destinationPath: s3://meta-postgres-backup
      s3Credentials:
        accessKeyId:
          key: AWS_ACCESS_KEY_ID
          name: postgres-backup
        region:
          key: AWS_REGION
          name: postgres-backup
        secretAccessKey:
          key: AWS_SECRET_ACCESS_KEY
          name: postgres-backup
      tags:
        backupRetentionPolicy: "expire"
      historyTags:
        backupRetentionPolicy: "keep"
    retentionPolicy: "30d"
  storage:
    size: 2Gi
    storageClass: ssd
  walStorage:
    size: 2Gi
    storageClass: ssd
