---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: meta
data:
  backup_database.sh: |
    #!/usr/bin/env bash

    set -e
    set -x

    export PGUSER=postgres
    export PGPASSWORD="${POSTGRES_PASSWORD}"
    export PGHOST=postgres

    dt=$(date '+%d/%m/%Y %H:%M:%S');
    fileDt=$(date '+%d_%m_%Y_%H_%M_%S');
    backUpFileName="$KUBEGRES_RESOURCE_NAME-backup-$fileDt.gz"
    backUpFilePath="$BACKUP_DESTINATION_FOLDER/$backUpFileName"

    echo "$dt - Starting DB backup of Kubegres resource $KUBEGRES_RESOURCE_NAME into file: $backUpFilePath";
    echo "$dt - Running: pg_dumpall -h $BACKUP_SOURCE_DB_HOST_NAME -U postgres -c | gzip > $backUpFilePath"

    pg_dumpall -h $BACKUP_SOURCE_DB_HOST_NAME -U postgres -c | gzip > $backUpFilePath

    if [ $? -ne 0 ]; then
      rm $backUpFilePath
      echo "Unable to execute a BackUp. Please check DB connection settings"
      exit 1
    fi

    echo "$dt - DB backup completed for Kubegres resource $KUBEGRES_RESOURCE_NAME into file: $backUpFilePath"
    echo "$dt - Uploading to S3"
    aws --endpoint-url "${AWS_ENDPOINT}" s3 cp "${backUpFilePath}" "${S3_BUCKET}/${S3_PREFIX}${backUpFileName}"
    rm -v "${backUpFilePath}"
