---
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: postgres
  namespace: meta
spec:
  image: rg.nl-ams.scw.cloud/rwx-im/postgres-wal-g:14.1-3
  imagePullSecrets:
  - name: rwx-im-scw-cr-auth
  backup:
    schedule: "3 */1 * * *"
    pvcName: meta-backup-tmp
    volumeMount: /var/lib/backup
  replicas: 2
  customConfig: postgres-config
  database:
    size: 2Gi
    storageClassName: ssd
  env:
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres-auth
        key: superUserPassword
  - name: POSTGRES_REPLICATION_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres-auth
        key: replicationUserPassword
  - name: AWS_ENDPOINT
    value: https://s3.eu-central-003.backblazeb2.com
  - name: S3_BUCKET
    value: s3://meta-data
  - name: S3_PREFIX
    value: backups/
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: postgres-backup
        key: AWS_ACCESS_KEY_ID
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: postgres-backup
        key: AWS_SECRET_ACCESS_KEY
