---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meta-cache
  namespace: meta
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-static
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meta-backup-tmp
  namespace: meta
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: hdd
