apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rwx-im-scw-cr-auth
  namespace: meta
spec:
  encryptedData:
    .dockerconfigjson: AgAuqedOlgHR6uD7mgXHBVndgUGB/yt75cZAg/PsNxes5ZqJqt48iiBUK8/qWQVYdr/AdWfRKcT9ljzLJV4WwFG6gZXvxttq1oR7UZ+9w4slvoZfwHZZqkB1tsDAl60xMX5XdiDG/WT62fkm21mQ4jbNb0g5l4Mv19/njIn3yDoMlssAFQtYGYr59QKNcGKV16NqJ3EcINPUzRf8n2CDieap2uYqZXOKtfEE1iJ/7+2kNP8z8uwedbFmZJpD3hKE1NZyo+J1mjlcVYUvtQVZxdwZcFZgfiRgrr8CQOk9peZBcgemkfvIUylxqWOk45of4cgOjc+IqCV5kHYsoF4+UbZI2yOxJdM2SF1JGuMYJn2pTb0SULea5n7VQo0ayzQG9mCOm3gznM/sz4wZIm0j89sogkNyGa8eLjfHKhLf4a4WA+GB8rl2UIo6DUE+sSCDqEuQkeD3+hnKRvqmcEK6w8P6vNTvwPJrQvgl+FHO3FeHbgeyXzcQ+cTmKz5++bNdnF8htvaihwSIBg4rZoVOJ6/EL922eTwT+vKN1w1BsEOmzonUf7f5xl9wQZDWgOTe2IkK/D7KMxUoo79kxZN//P94KgkPpTvDlm3NyM06PH+GTq9jRQ5gMAT5hv22PtF5diqtzRxcWJynhBKm9pHI+qG+ZwQUsR6HLOiTgDqhBGipkzPpTmK7K8yaK6Hpu4fyIGlHur/cMqcJ5vkt8WXvxwQhelnP4Z2dkZYbVAmbA3fd9gUvwrHVzu0w+P5PYr95HJ3kdC+PzoQkkUHOdExABVU7wmlHaoUNE3FDOBlylgxzdUcoXHB5Gb6Aisp/kfO+kpIseo35OyONgtShKF8UGHvtiyB6kaoBaBjrRy211GfQ6hZyN59T
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: rwx-im-scw-cr-auth
      namespace: meta
    type: kubernetes.io/dockerconfigjson

