apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: meta-deployments-workflow-creator-binding
  namespace: meta-deployments
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workflow-creator
subjects:
- kind: ServiceAccount
  name: meta-deployments-workflow-creator
  namespace: mkroman-github-events
